###
GET http://localhost:3001/data/M_Temperatura/2/false

###
POST https://sunandchirpstack.ddns.net:8080/api/devices/2cf7f1203230a466/queue
Content-Type: application/json
Accept: application/json
Grpc-Metadata-Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5X2lkIjoiNDExMzkxZDItMGY0ZC00MTAzLTkwZjAtNDE1NTQ0ZjA4YTljIiwiYXVkIjoiYXMiLCJpc3MiOiJhcyIsIm5iZiI6MTY0MjYxNjIwMCwic3ViIjoiYXBpX2tleSJ9._a7OBvSyrw0z-Gdo36W2SgjoVfe5syE2ZgKsl-13qes

{
  "deviceQueueItem": {
    "confirmed": true,
    "data": "AA==",
    "devEUI": "2cf7f1203230a466",
    "fCnt": 0,
    "fPort": 3
  }
}

###
POST http://localhost:3001/data
Content-type: application/json

{
    "name": "anything",
    "released_year": 2022,
    "githut_rank": 100,
    "pypl_rank": 100,
    "tiobe_rank": 99
}

###
PUT  http://localhost:3001/data/temperatura/1
Content-type: application/json

{
    "name": "javascript",
    "released_year": 2022,
    "githut_rank": 100,
    "pypl_rank": 100,
    "tiobe_rank": 99
}

###
DELETE http://localhost:3001/data/18


